apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # This pulls the Controller instance definition
  - https://github.com/redhat-cop/gitops-catalog/ansible-automation-platform/aggregator/overlays/default?ref=main

# You can overlay your specific tweaks here (like admin password) 
# BUT for now, let the catalog do the heavy lifting.